# Generated by Django 3.2.12 on 2022-04-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stage',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='board',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='stage',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
