# Generated by Django 3.2.12 on 2022-04-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20220418_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='board',
        ),
        migrations.AlterField(
            model_name='stage',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
