# Generated by Django 4.0.1 on 2022-02-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
