# Generated by Django 4.0.1 on 2022-02-11 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_schedule_email_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='minutes',
        ),
        migrations.AddField(
            model_name='schedule',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
