# Generated by Django 4.0.1 on 2022-02-11 06:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_remove_schedule_hours_remove_schedule_minutes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
