# Generated by Django 4.0.1 on 2022-02-11 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_alter_schedule_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='email_sent',
        ),
        migrations.AddField(
            model_name='schedule',
            name='prev_sent_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
